"""
Pydantic schemas for structured syndromic surveillance signals.
These define the exact JSON structure MedGemma 4B will be fine-tuned to produce.
"""

from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum
from datetime import datetime


class SeverityLevel(str, Enum):
    MILD = "mild"
    MODERATE = "moderate"
    SEVERE = "severe"
    CRITICAL = "critical"


class AgeGroup(str, Enum):
    NEONATE = "neonate"         # 0-28 days
    INFANT = "infant"           # 1-11 months
    CHILD = "child"             # 1-4 years
    SCHOOL_AGE = "school_age"   # 5-14 years
    ADOLESCENT = "adolescent"   # 15-19 years
    ADULT = "adult"             # 20-59 years
    ELDERLY = "elderly"         # 60+


class SyndromicSignal(BaseModel):
    """Core extraction output from a single clinical encounter."""

    # Symptom extraction
    symptoms: list[str] = Field(
        description="Normalized list of symptoms/signs observed"
    )
    symptom_onset_days: Optional[int] = Field(
        None, description="Days since symptom onset"
    )
    symptom_duration_days: Optional[int] = Field(
        None, description="Duration of symptoms in days"
    )

    # Syndromic classification
    syndrome_category: str = Field(
        description="Primary WHO syndromic surveillance category"
    )
    secondary_syndromes: list[str] = Field(
        default_factory=list,
        description="Additional possible syndrome categories"
    )

    # Clinical severity
    severity: SeverityLevel = Field(
        description="Clinical severity assessment"
    )

    # Demographics
    age_group: AgeGroup = Field(
        description="Patient age group"
    )
    sex: Optional[str] = Field(
        None, description="Patient sex if mentioned (male/female)"
    )

    # Coding
    icd10_codes: list[str] = Field(
        description="Relevant ICD-10 codes"
    )
    reportable_conditions_flagged: list[str] = Field(
        default_factory=list,
        description="Reportable conditions this encounter may signal"
    )

    # Epidemiological context
    travel_history: Optional[str] = Field(
        None, description="Recent travel mentioned"
    )
    contact_history: Optional[str] = Field(
        None, description="Known contact with similar cases"
    )
    cluster_indicator: bool = Field(
        False, description="Whether patient reports others with similar symptoms"
    )

    # Metadata
    confidence_score: float = Field(
        ge=0.0, le=1.0,
        description="Model confidence in extraction (0-1)"
    )


class ClinicalEncounter(BaseModel):
    """Full clinical encounter record with metadata."""

    encounter_id: str
    timestamp: datetime
    location_lat: Optional[float] = None
    location_lon: Optional[float] = None
    district: Optional[str] = None
    facility_name: Optional[str] = None

    # Raw inputs
    narrative_text: str = Field(
        description="Free-text clinical narrative (from CHW or transcribed speech)"
    )
    has_image: bool = False
    image_path: Optional[str] = None

    # Extracted signal
    syndromic_signal: Optional[SyndromicSignal] = None


class SurveillanceAlert(BaseModel):
    """Alert generated by the surveillance analytics agent."""

    alert_id: str
    alert_level: str  # watch, warning, emergency
    syndrome_category: str
    district: str

    # Signal summary
    case_count_current_week: int
    case_count_baseline: float
    ratio_to_baseline: float

    # Temporal
    trend: str  # increasing, stable, decreasing
    weeks_above_threshold: int

    # Generated content (by MedGemma 27B)
    situation_summary: str
    recommended_actions: list[str]
    evidence_summary: str

    # Forecast
    forecast_next_week: Optional[float] = None
    forecast_confidence_interval: Optional[tuple[float, float]] = None

    timestamp: datetime


class FHIRSurveillanceReport(BaseModel):
    """Simplified FHIR-compatible report structure."""

    resource_type: str = "Bundle"
    report_id: str
    report_date: datetime
    reporting_facility: str
    reporting_district: str
    period_start: datetime
    period_end: datetime

    # Aggregated counts per syndrome
    syndrome_counts: dict[str, int]

    # Alerts
    active_alerts: list[SurveillanceAlert]

    # Narrative
    narrative_summary: str
